---
name: FlySpeed
version: 1.0.0
main: GameParrot\FlySpeed\FlySpeed
api: 5.0.0
src-namespace-prefix: GameParrot\FlySpeed
author: GameParrot
description: Change players fly speed
website: https://github.com/GameParrot/FlySpeed
...
